### ISSUE TITLE
One request

### ISSUE THREAD

**Issue by 805557409** [Pjbomb2/Realtime-Compute-Shader-Unity-PathTracer#4]
Could you please upload a complete Unity project file? please

**Comment by trsh** [comment]
@805557409 what kind of actually? URP, HDRP or Core?

**Comment by 805557409** [comment]
Is urp OK?  As long as it can show good results. It's better to have some sample scenarios, because I'm a novice.  thank you very much.

**Comment by trsh** [comment]
@805557409 I am also trying to play with this lib, but nothing works. I am on 2022.1.16. The settings from PathTracer aren't saving. I check a box, I reopen and its not checked. When I press Play, it feels I just get regular Unity rendering.

**Comment by trsh** [comment]
Core seems to work better

**Comment by 805557409** [comment]
Really? Do you want to create a new Cinematic Studio project? How did you do it?

**Comment by trsh** [comment]
@805557409 just create Core 3d project (no urp or hdrp), fallow the guidlines in readme, then import package and open its contained demo scene.

**Comment by 805557409** [comment]
OK, let me try. Can it really achieve the effect shown in the picture?

**Comment by trsh** [comment]
@805557409 Yes, but its result of accumulation. Like you wait for 3-4 sec. When you move its all noisy and current denoisers don't do a good job,

**Comment by 805557409** [comment]
I created the Core 3d project and fall the guidelines in readme as you said, but whenever I click play, Uniry crashes.

**Comment by trsh** [comment]
@805557409 what version of Unity do you have?

**Comment by 805557409** [comment]
It shows the error.
There are more uavs (10) than the maximum supported (8) in ComputeShader 'RayTracingShader' kernel 'kernel_ shade'.

**Comment by 805557409** [comment]
Could you share the complete project file? I am a novice.please

**Comment by trsh** [comment]
@805557409 author said that this error and lots of warnings, that end with dx11 are expected due some limitations of Unity, Either way, if you press Play it should run.

If you get this: `IndexOutOfRangeException: Index was outside the bounds of the array.`. Then rebuild BVH from PathTracer menu. There is a button top, left. I am currently no by mine computer.

**Comment by 805557409** [comment]
Don't be in a hurry. You can upload when you are free. Thank you for your help.

**Comment by trsh** [comment]
@805557409 still doesn't work?

**Comment by 805557409** [comment]
Yes, it seems so far.

**Comment by crizzler** [comment]
> Yes, it seems so far.

I contacted the dev and the unity crash is caused by the atmosphere generator script. Go to line 355 in the script and change the int NumScatteringOrder = 12 to something like 1. I can't go any higher than 4 with objects in the scene.

**Comment by trsh** [comment]
Wasn't the case for me. But I tested just the provided scene from package

**Comment by 805557409** [comment]
> > 是的，似乎到目前为止。
> 
> 我联系了开发人员，Unity崩溃是由大气发生器脚本引起的。转到脚本中的第 355 行，并将整数 NumScatteringOrder = 12 更改为类似于 1 的值。对于场景中的物体，我不能高于4。
In my AtmosphereGenerator script, NumStrateringOrder is 4. When I change it to 1, the error "There are more uavs (10) than the maximum supported (8) in ComputeShader 'RayTracingShader' kernel 'kernel_ shade'" still appears

**Comment by trsh** [comment]
> > Yes, it seems so far.
> 
> I contacted the dev and the unity crash is caused by the atmosphere generator script. Go to line 355 in the script and change the int NumScatteringOrder = 12 to something like 1. I can't go any higher than 4 with objects in the scene.

Interesting. I took a fresh clone this morning and I already had `NumScatteringOrder  = 4`. Tried to change it to 1. But still having this error at runtime:

```
There are more uavs (10) than the maximum supported (8) in ComputeShader 'RayTracingShader' kernel 'kernel_shade'.
```

however, it doesn't seem to be a blocker, as the scene is rendering. But it could indicate, that some part is not working.

**Comment by 805557409** [comment]
> 

How did you solve it? Don't you work normally? I also use the scenario given by the project. I didn't change it.

**Comment by trsh** [comment]
> In my AtmosphereGenerator script, NumStrateringOrder is 4. When I change it to 1, the error "There are more uavs (10) than the maximum supported (8) in ComputeShader 'RayTracingShader' kernel 'kernel_ shade'" still appears

The error is there. But the scene works :P . Doesn't it? You have to press Play.

**Comment by trsh** [comment]
![2022-09-18_193306](https://user-images.githubusercontent.com/3727523/190917917-49a6b462-5ad9-4196-95c3-8d42d6efb265.png)

**Comment by Pjbomb2** [comment]
ok so
what do you mean by completely unity project file?  the reason why I dont think I have yet is cuz I still upload to github from the web, so I cant upload large files
the uav error is because unity doesnt let you dissable dx11 even if you dont use it
The numscatteringorder turs out is way more intensive than I thought, I need to add something to either spread it out over multiple frames or make it accessable from the settings...

**Comment by 805557409** [comment]
So does it really work in the scene? I followed the tutorial to add new scenes, but the effect seems to be very good. I didn't add a new shader

**Comment by 805557409** [comment]
> @805557409 author said that this error and lots of warnings, that end with dx11 are expected due some limitations of Unity, Either way, if you press Play it should run. If you focus screen (click on it) and press t, you can navigate in this play mode.
> 
> If you get this: `IndexOutOfRangeException: Index was outside the bounds of the array.`. Then rebuild BVH from PathTracer menu. There is a button top, left in this menu.
> 
> I am currently not by mine computer.

@trsh How do I contact the author?

**Comment by trsh** [comment]
> So can it really achieve the effect in the picture? I added a new scene according to the tutorial, but the screen seems very ordinary. I didn't add a new shader.

You asked this question before and I did answer -> https://github.com/Pjbomb2/Realtime-Compute-Shader-Unity-PathTracer/issues/4#issuecomment-1250202682

I can comment further, as I played only with provided scene.

**Comment by 805557409** [comment]
> > Yes, it seems so far.
> 
> I contacted the dev and the unity crash is caused by the atmosphere generator script. Go to line 355 in the script and change the int NumScatteringOrder = 12 to something like 1. I can't go any higher than 4 with objects in the scene.

@crizzler How do I contact the author?

**Comment by 805557409** [comment]
> > 那么它真的能达到画面中的效果吗？我根据教程添加了一个新的场景，但屏幕看起来很普通。我没有添加新的着色器。
> 
> 你以前问过这个问题，我确实回答了-> [#4 （评论）](https://github.com/Pjbomb2/Realtime-Compute-Shader-Unity-PathTracer/issues/4#issuecomment-1250202682)
> 
> 我不能进一步评论，因为我只玩了提供的场景。



> > So can it really achieve the effect in the picture? I added a new scene according to the tutorial, but the screen seems very ordinary. I didn't add a new shader.
> 
> You asked this question before and I did answer -> [#4 (comment)](https://github.com/Pjbomb2/Realtime-Compute-Shader-Unity-PathTracer/issues/4#issuecomment-1250202682)
> 
> I can not comment further, as I played only with provided scene.

Well, thank you all the same

**Comment by trsh** [comment]
There is discord ID in readme. However I would suggest you to first learning basic of unity and c# programming, them shaders and compute shaders. Otherwise you will not make much sense out off all this, and will keep asking infinite questions. PathTracing with compute shaders is not for Novices (as you called your self).

**Comment by 805557409** [comment]
> There is author discord ID in readme. However I would suggest you to first learning basic of unity and c# programming, them shaders and compute shaders, then light transport stuffs (maybe code your first raw path tracer). Otherwise you will not make much sense out off all this, and will keep asking infinite questions. PathTracing with compute shaders is not for Novices (as you called your self), not by far.

OK, I have the basic knowledge of graphics. I mean I'm a novice in PathTracing (I only know theoretical knowledge), so I want to learn the code of pathtracing.

**Comment by trsh** [comment]
> > There is author discord ID in readme. However I would suggest you to first learning basic of unity and c# programming, them shaders and compute shaders, then light transport stuffs (maybe code your first raw path tracer). Otherwise you will not make much sense out off all this, and will keep asking infinite questions. PathTracing with compute shaders is not for Novices (as you called your self), not by far.
> 
> OK, I have the basic knowledge of graphics. I mean I'm a novice in PathTracing (I only know theoretical knowledge), so I want to learn the code of pathtracing.

If you are new to path tracing/raytracing I would advice to complete these:

https://raytracing.github.io/
https://www.scratchapixel.com/lessons/3d-basic-rendering/global-illumination-path-tracing/global-illumination-path-tracing-practical-implementation


If you don't know c++, you can try to do same in Unity (will take some brain to figure out).

Then create your first compute shader: https://github.com/cinight/MinimalCompute/tree/master/Assets/ComputeUAVTexture -> this is minimal example. You must know how thread, group ids work -> https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sv-dispatchthreadid .

Then you will be able to make sense out of all this. Thats my biased opinion. Good luck on your path.

**Comment by 805557409** [comment]
> > > There is author discord ID in readme. However I would suggest you to first learning basic of unity and c# programming, them shaders and compute shaders, then light transport stuffs (maybe code your first raw path tracer). Otherwise you will not make much sense out off all this, and will keep asking infinite questions. PathTracing with compute shaders is not for Novices (as you called your self), not by far.
> > 
> > 
> > OK, I have the basic knowledge of graphics. I mean I'm a novice in PathTracing (I only know theoretical knowledge), so I want to learn the code of pathtracing.
> 
> If you are new to path tracing/raytracing I would advice to complete these:
> 
> https://raytracing.github.io/ https://www.scratchapixel.com/lessons/3d-basic-rendering/global-illumination-path-tracing/global-illumination-path-tracing-practical-implementation
> 
> If you don't know c++, you can try to do same in Unity (will take some brain to figure out).
> 
> Then create your first compute shader: https://github.com/cinight/MinimalCompute/tree/master/Assets/ComputeUAVTexture -> this is minimal example. You must know how thread, group ids work -> https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sv-dispatchthreadid .
> 
> Then you will be able to make sense out of all this. Thats my biased opinion. Good luck on your path.

Thank you very much.

**Comment by Pjbomb2** [comment]
I think this is taken care of? If I am wrong, feel free to re-open it and let me know!
