### ISSUE TITLE
Max supported UAV's in compute shaders exceeded?

### ISSUE THREAD

**Issue by Firesampo** [Pjbomb2/Realtime-Compute-Shader-Unity-PathTracer#5]
Hey,

Getting this error+ a cascaded flow of random issues after it. Any clue what might cause this? Trying to run this  on RTX 2080 laptop + Unity 2021.3.10f1.

There are more uavs (16) than the maximum supported (8) in ComputeShader 'RayTracingShader' kernel 'kernel_shade'.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
RayTracingMaster:Render (UnityEngine.RenderTexture) (at Assets/Resources/RayTracingMaster.cs:803)
RayTracingMaster:OnRenderImage (UnityEngine.RenderTexture,UnityEngine.RenderTexture) (at Assets/Resources/RayTracingMaster.cs:908)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

This then turns into a bunch of issues, such as

ArgumentException: SetData(): Accessing 1980 bytes at offset 0 for Buffer of size 1800 bytes is not possible.
UnityEngine.ComputeBuffer.SetData[T] (System.Collections.Generic.List`1[T] data) (at <88d854ea2c91426ebc464f01cd71aa85>:0)
RayTracingMaster.RebuildMeshObjectBuffers () (at Assets/Resources/RayTracingMaster.cs:307)
RayTracingMaster.OnRenderImage (UnityEngine.RenderTexture source, UnityEngine.RenderTexture destination) (at Assets/Resources/RayTracingMaster.cs:905)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

Is this somehow related to some GPU's not supporting 16 UAV's or something?

br,
Sami

**Comment by Firesampo** [comment]
Tested this also on a desktop with A5000 GPU, which should be roughly the equivalent of 3080, same issue.

**Comment by Pjbomb2** [comment]
hmmm ok a few things to try, first try building the BVH before starting, and make sure All Object Built is green in the settings
I assume you already set it to dx12?
the UAV is a known issue but it only affects dx11(hence why I am on dx12 instead), but you cant silence them

**Comment by Firesampo** [comment]
Yeah, I'm on DX12. An older version of the package seemed to work, so it must be some glitch in the latest build.

**Comment by Pjbomb2** [comment]
try the latest latest version I just uploaded
